### ISSUE TITLE
Server crash in 1.12.2

### ISSUE THREAD

**Issue by TheGreatCatAdorer** [PersonTheCat/ore_stone_variants#100]
[crash-2020-11-10_18.07.09-server.txt](https://github.com/PersonTheCat/ore_stone_variants/files/5520707/crash-2020-11-10_18.07.09-server.txt)
The server goes into a loop when loading into a world.  Disabling FoamFix has been tried and does not work.

**Comment by TheGreatCatAdorer** [comment]
[crash-2020-11-10_18.52.36-client.txt](https://github.com/PersonTheCat/ore_stone_variants/files/5520840/crash-2020-11-10_18.52.36-client.txt)
The game crashes with only OSV and Forge loaded.

**Comment by TheGreatCatAdorer** [comment]
Ignore that it is on client now.  The same bug has happened.

**Comment by PersonTheCat** [comment]
Wow, fascinating. Let me take a look right now. Surprised I haven't seen this one yet.

**Comment by PersonTheCat** [comment]
Discovered some inconsistent logic between the different versions that would create this issue when `bgImitation` is disabled. Try this new build out when you get the chance and tell me if the issue goes away. Thanks for your help!

[Ore Stone Variants-5.8-1.12.zip](https://github.com/PersonTheCat/ore_stone_variants/files/5520934/Ore.Stone.Variants-5.8-1.12.zip)

**Comment by TheGreatCatAdorer** [comment]
I turned bgImitation off because I had spawned in the desert once and it made all the cave entrances collapse.
