### ISSUE TITLE
Broken textures in 1.16.3

### ISSUE THREAD

**Issue by TheGreatCatAdorer** [PersonTheCat/ore_stone_variants#101]
All OSV textures are not working, but all other textures are.
_[modloading-worker-2/DEBUG] [osv/]: Reflection error: field "GSON_INSTANCE" not found in mappings. Trying index...
[Render thread/DEBUG] [osv/]: Reflection error: field "material" not found in mappings. Trying index...
[Render thread/DEBUG] [osv/]: Reflection error: field "blocksMovement" not found in mappings. Trying index...
[Render thread/DEBUG] [osv/]: Reflection error: field "soundType" not found in mappings. Trying index...
[Render thread/DEBUG] [osv/]: Reflection error: field "resistance" not found in mappings. Trying index...
[Render thread/DEBUG] [osv/]: Reflection error: field "hardness" not found in mappings. Trying index...
[Render thread/DEBUG] [osv/]: Reflection error: field "ticksRandomly" not found in mappings. Trying index...
[Render thread/DEBUG] [osv/]: Reflection error: field "slipperiness" not found in mappings. Trying index...
[Render thread/DEBUG] [osv/]: Reflection error: field "speedFactor" not found in mappings. Trying index...
[Render thread/DEBUG] [osv/]: Reflection error: field "jumpFactor" not found in mappings. Trying index...
[Render thread/DEBUG] [osv/]: Reflection error: field "lootTable" not found in mappings. Trying index...
Render thread/DEBUG] [osv/]: Reflection error: field "isSolid" not found in mappings. Trying index...
[Render thread/DEBUG] [osv/]: Reflection error: field "variableOpacity" not found in mappings. Trying index..._
This was found in debug log.
Also many variations on
_[Worker-Main-4/WARN] [net.minecraft.client.renderer.model.ModelBakery/]: Exception loading blockstate definition: osv:blockstates/gold_ore_gravel.json: java.io.FileNotFoundException: osv:blockstates/gold_ore_gravel.json
[Worker-Main-4/WARN] [net.minecraft.client.renderer.model.ModelBakery/]: Exception loading blockstate definition: 'osv:blockstates/gold_ore_gravel.json' missing model for variant: 'osv:gold_ore_gravel#dense=false'
[Worker-Main-4/WARN] [net.minecraft.client.renderer.model.ModelBakery/]: Exception loading blockstate definition: 'osv:blockstates/gold_ore_gravel.json' missing model for variant: 'osv:gold_ore_gravel#dense=true'_
[debug.log](https://github.com/PersonTheCat/ore_stone_variants/files/5524963/debug.log)
![2020-11-11_10 23 01](https://user-images.githubusercontent.com/74263017/98831544-b088e800-2409-11eb-81c9-21ae9e53d983.png)
![2020-11-11_10 23 07](https://user-images.githubusercontent.com/74263017/98831546-b088e800-2409-11eb-9755-8c4d447b90cf.png)

**Comment by PersonTheCat** [comment]
Hey, sorry I never responded to this. I was never able to reproduce the issue. If you're still experiencing it, come join us on Discord and we can try to work it out.

https://discord.gg/UNsXfvA
