### ISSUE TITLE
Registering ores with mod items in their loot tables crashes on 1.16.3

### ISSUE THREAD

**Issue by clockler** [PersonTheCat/ore_stone_variants#104]
Registering the OSV blocks causes the ore's loot tables to be loaded immediately, which will fail if the loot table contains any modded items. Changing the loot table in question to drop a vanilla item rather than a modded one allows the loot table to load, so my assumption is that modded items aren't registered yet, since the item in question definitely eventually exists.

Crash log: [crash-2020-11-19_19.57.21-fml.txt](https://github.com/PersonTheCat/ore_stone_variants/files/5565584/crash-2020-11-19_19.57.21-fml.txt)

What I've tried:
* Setting the `RegistryHandler#registerBlocks` event priority to lowest, which doesn't seem to alter this behaviour.
* Changing `RegistryHandler#registerBlocks` to use a `DeferredRegister` instead - doesn't alter this behaviour, definitely defers registration as the call to `BaseOreVariant#updatePostRegister` throws with this change.

**Comment by PersonTheCat** [comment]
Presets now get loaded even later than they previously were in 5.11, which should mitigate this issue even more. I'm gonna go ahead and close it.
