### ISSUE TITLE
[1.12.2] Crash on Startup - Rustic related

### ISSUE THREAD

**Issue by juraj-hrivnak** [PersonTheCat/ore_stone_variants#108]
- Here is the log _(from MultiMC- with modlist)_..
https://paste.ee/p/9XE8Z

It says:
`java.lang.RuntimeException: There is no block named "rustic:slate." Fix your block group.
    at`

> _side note: hope this is not my fault :D_

**Comment by juraj-hrivnak** [comment]
My fault :D

**Comment by PersonTheCat** [comment]
@juraj-hrivnak Hey, let's get this updating in case someone sees it on Google later. Mind sharing how you fixed it?

**Comment by juraj-hrivnak** [comment]
Of course, sorry :D. The problem was that I disabled the `rustic: slate` in rustic config. And forgot about it.
It crashed because slate was not loaded!

**Comment by PersonTheCat** [comment]
Thanks! I appreciate that. [Come join us on Discord](https://discord.gg/UNsXfvA), if you need anything else. I can respond more quickly there.
