### ISSUE TITLE
JEI Compatibility Issue

### ISSUE THREAD

**Issue by WenXin20** [PersonTheCat/ore_stone_variants#110]
`Minecraft v1.16.4`
`Forge v35.1.36`
`OSV v5.11`

I decided it would be better to create a new issue for this. I got a crash in JEI when searching `@osv` and when going to the creative tab for the dense ore variants. It seems to be related to adding sandstone to the blockgroup. The reports also mention optifine (pre12) and obfuscate (required for the vehicles mod).
[JEI Crash Report](https://gist.github.com/WenXin20/d92b2f6357fc2fdf93a5f5a013134d05)
[Creative Tab Crash Report](https://gist.github.com/WenXin20/3fc22776932abca2177e6347756db308)

**Comment by PersonTheCat** [comment]
I don't consider this a bug since it has to do with other mods, but I will look into it. 

This is a reminder that **I have not experienced this problem and cannot reproduce it.**

**Comment by WenXin20** [comment]
Yes, I know. I'll see if I can find which mod causes it.

**Comment by WenXin20** [comment]
Any idea what mods could potentially cause this? I tried replicating it in a fresh instance, but I've had no luck with the mods mentioned in the crash reports.

**Comment by WenXin20** [comment]
I still haven't figured out what caused the crash, I tried splitting the modpack up to check for what could cause it, but none of the mods crashed it. The only thing I haven't tried is on a server. Were you able to test on a server?

**Comment by PersonTheCat** [comment]
No, I didn't think about that. It shouldn't crash because none of the textures or block models are actually loaded on servers, but I'll give it a try.

**Comment by WenXin20** [comment]
I was able to replicate the crash in singleplayer with this modpack everytime. I've tried all day yesterday to narrow down the mods, but I've been unable to, which has been incredibly frustrating. I'm wondering if the crash is happening because of the amount of items listed in JEI.
https://drive.google.com/file/d/1hnjwZ3eBxr-o69xCf54CA76JDb7MCZAi/view?usp=sharing

**Comment by PersonTheCat** [comment]
Just curious, did you try it without OSV? If so, did it still crash? If it is only crashing with OSV installed, I will take another look tonight. If not, this is probably a bug with JEI and not OSV.

**Comment by WenXin20** [comment]
No, I haven't yet. But it crashes when opening the osv creative tab too.
Also, this line: 
https://gist.github.com/WenXin20/3fc22776932abca2177e6347756db308#file-osv_crash-txt-L68

**Comment by PersonTheCat** [comment]
@WenXin20 Can you confirm if this issue still occurs?

**Comment by WenXin20** [comment]
No crashes so far with jei. I forgot about this to be honest. :D

**Comment by PersonTheCat** [comment]
Awesome! Thanks for the quick response!
