### ISSUE TITLE
[crash] (1.16) Missing file exception 

### ISSUE THREAD

**Issue by Skaphegor** [PersonTheCat/ore_stone_variants#116]
This crash happens to one of my mates whilst trying to launch the game.
I have the same pack it doesn't happen to me. He is on MacOSX.

Log: https://pastebin.com/Yka8Whst

Pack: https://www.curseforge.com/minecraft/modpacks/skapack

**Comment by PersonTheCat** [comment]
Hey, there! This should pretty much be impossible, since it means a required file wasn't in the jar. My suggestion would be to either redownload this version of the mod, or try the new 6.0 version that came out yesterday. If it's still happening, let me know.
