### ISSUE TITLE
Feature Request. Only read .hjson files from Ores and Stones config dir.

### ISSUE THREAD

**Issue by wmrojer** [PersonTheCat/ore_stone_variants#118]
Currently the mod is reading ALL files from the config directories for Ores and Stones. Meaning it will also read any .bak files editors make when you save changes. I can't count the number of times i fixed a bug and forgotten to manually remove the .bak file just the get the same error message again when starting up the game.

I'm currently on version 1.12.2 and I don't know if you still support those old versions. But it seems lots of forge mods are stuck at 1.12 still so.

**Comment by PersonTheCat** [comment]
Yeah, this is a pretty small feature and a reasonable QOL improvement. I can do this.

**Comment by PersonTheCat** [comment]
Just an update on this: it's gonna be a few more days until I can start on this. Still very deep in Cave Generator at the moment and want to fix several bugs there first. I will work on only ready `.hjson` **and** `.json` files, ,as well as these other tickets, sometime time this week while I am off work.

**Comment by PersonTheCat** [comment]
Just finished the new Cave Generator update and will resolve all of these issues this week. Sorry for the bad estimate before.

**Comment by PersonTheCat** [comment]
This was resolved in [bd3a0270](https://github.com/PersonTheCat/ore_stone_variants/commit/bd3a0270fcd8548b01b07e9ef42f08e39ca7dbf1). 

Since several of these issues are from the same user, I'll supply a build when they're all complete in the comments of #120.
