### ISSUE TITLE
Inconsistent Crash on Load

### ISSUE THREAD

**Issue by judicius** [PersonTheCat/ore_stone_variants#122]
This seems to happen the first time the pack is loaded with OSV, if I close the instance and reload the pack it usually works afterwards.

Forge: 36.1.4
OSV: 6.1
Minecraft 1.16.5

https://gist.github.com/judicius/3876b940ec174906473263e8da312870

**Comment by PersonTheCat** [comment]
Thanks! I'm aware of this issue. It has to do with asset generation. Assets don't generate every time you start your game, which I believe is why this is so inconsistent. I'll be working on OSV 1.12 again in the next two weeks or so and will take a look at it then.

**Comment by PersonTheCat** [comment]
This should be completely impossible to occur in 6.2. I'll close this now.
