### ISSUE TITLE
Server crash after world is finished generating

### ISSUE THREAD

**Issue by pm065** [PersonTheCat/ore_stone_variants#127]
mod list: https://paste.gg/p/anonymous/925b9d82cc444bb5ad723f6a59c6cb9a
crash report: https://paste.gg/p/anonymous/0c825ed76283446e968ace4fba2f2e92
After generating a new world, just as recipes are loading, the game freezes and hangs indefinitely. 

versions:
MC 1.16.5
FORGE 36.1.32
OSV 6.2

**Comment by pm065** [comment]
For now I'll disable OSV and try to remember to reenable it when this bug report is resolved (:

**Comment by pm065** [comment]
Erm... apparently this isn't OSV. Huh.

**Comment by pm065** [comment]
Okay, it is, I got confused for a moment by an unrelated Quark issue. The problem is with OSV. Sorry for the spam!

**Comment by PersonTheCat** [comment]
I'm _pretty_ sure this is only possible if some other mod has made changes to `RecipeManager#recipes` and thus is not a bug with OSV. 
I'll take another look tonight just to double check, but honestly, I can't fix this unless I know which mod is causing the problem. 
If you have the time, please confirm whether this crash still occurs for you **with no other mods present**.

**Comment by pm065** [comment]
Okay, just a minute...

**Comment by pm065** [comment]
I can confirm that it does not happen on its own. I suspect Extended Crafting since the crashes started after adding that mod.

**Comment by PersonTheCat** [comment]
Huh. Cool, thanks!
