### ISSUE TITLE
Fix compatibility for Forge Endertech's Large Ore Deposits.

### ISSUE THREAD

**Issue by Kaleidio** [PersonTheCat/ore_stone_variants#129]
Your generator constantly throws error, leading to the server using as much as 5 Gigabytes per second throughput, and logspamming until it's in the hundreds of megabytes.

it's so ungodly large...it even says optifine threw a few opengl exceptions with your renderer too.

[19:54:35] [Server thread/ERROR]: Error adding element: Value 64 outside of range [0:10]
over.  and over.  and over.  for millions of lines.

Using Kaleidio's Battle Pack at the time.

**Comment by PersonTheCat** [comment]
This is a user error and should be fixed. One of your ores has a cluster size of > 64, which is not allowed. I think it's actually supposed to crash. You need to reduce your cluster size. 

In the future, I will support larger cluster sizes in the form of a new generator, but this is an unrelated ticket. 

I'll leave this open temporarily for visibility.

**Comment by Kaleidio** [comment]
That's not my problem.  That's caused by a mod called Large Ore Deposits.

Relabel this as "add compatibility for Forge Endertech Large Ore Deposits" please.

**Comment by PersonTheCat** [comment]
Sure. Thanks for the clarification.
