### ISSUE TITLE
Missing Textures

### ISSUE THREAD

**Issue by SextupleTap** [PersonTheCat/ore_stone_variants#14]
The mod gives me a missing texture (black and purple checker board) for the ores added...

But the particles that come from the blocks (mining/breaking particles) are correct/match their stone variant and are not the missing texture "texture."

![2018-05-24_15 02 06](https://user-images.githubusercontent.com/36042986/40506005-05408866-5f64-11e8-8954-e4f9d7ed3a22.png)

Is a mod list necessary?

If so then please ask (I am telling to ask since my mods list is very large).

I have not checked logs yet either but if you need those I can also provide them.

The strange part is not all the textures are broken, only some of them are broken...

**Comment by SextupleTap** [comment]
I know that we are discussing this in the curse forge comments of the mod page. However, if you would like to migrate over here then I will gladly do so (if the issue is not resolved by the time you end up seeing this issue on github).

**Comment by PersonTheCat** [comment]
For the record, this issue appears to have been resolved. I would like to continue investigating to find out why it wasn't working, but I still just don't have enough information to go by. So there isn't much I can do and I'll be closing this issue as a result. 

Thanks for your help!
