### ISSUE TITLE
Normal redstone spam

### ISSUE THREAD

**Issue by pupnewfster** [PersonTheCat/ore_stone_variants#20]
I decided to open an issue for this as I have managed to track down WHAT causes it to go off even though I am not sure where it happens in the code.

Every time that I look at a non lit redstone ore_stone_variant ore it fires the message until I stop looking at the block.

**Comment by PersonTheCat** [comment]
Damn, really? I never noticed. I'm not even aware of any methods in Block that run when blocks are looked at, but that does help. I'll look at it. I guess I could always just disable it, but it's there for a reason. It's supposed to indicate that something is happening when it should not.

**Comment by pupnewfster** [comment]
Not sure, the majority of ores I use are dynamicly created ones but it happens with the vanilla ores also. The only other thing I can think of that MAY be calling some method for blocks when looking at them is I use The One Probe which is like WAILA for showing what block someone is looking at.

**Comment by PersonTheCat** [comment]
Tried it. That was it. Let me run their mod through a decompiler or something and see if I can figure it out.

**Comment by pupnewfster** [comment]
If you mean run TOP through a decompiler you could just look here https://github.com/McJtyMods/TheOneProbe as it is open source.

**Comment by pupnewfster** [comment]
Closing this given it is fixed in the next version as I no longer experience this with the test build you sent me.
