### ISSUE TITLE
Mod Support set False Texture Failure

### ISSUE THREAD

**Issue by EPSIL0N** [PersonTheCat/ore_stone_variants#23]
it would seem a recent update changed how the texture system is working.

If I use the default config I get working textures in all the stone variants but if I set Minecraft to false in the mod support section and instead write in " minecraft, stone " in the variant adder I get fail texture in jei and in game.

I believe before the same setup just disabled the autogeneration of the andesite and diorite and basic stone variants but still allowed the stone to be added back manually on the list.

**Comment by PersonTheCat** [comment]
Thanks. This is very helpful. Textures are generated slightly earlier now, so I had to use the the OreProperties to generate them instead of which blocks were registered, like before. My bad. I know of an easy fix, but let me see if I can come up with something better when I get back.

**Comment by PersonTheCat** [comment]
I may go ahead and close this issue. Please reopen it if the problem has not been resolved for you.
