### ISSUE TITLE
Crash on loading without resources generated

### ISSUE THREAD

**Issue by pupnewfster** [PersonTheCat/ore_stone_variants#27]
https://paste.dimdev.org/atekotosuf.mccrash
And a different crash I am getting sometimes instead while trying to load (using the 3.0.3 version you sent) https://paste.dimdev.org/emoderavah.mccrash

List of custom ores: https://i.gyazo.com/97a98ac71e5e57a1c112bddf13b94dbe.png

**Comment by PersonTheCat** [comment]
Are any of those new since you started crashing, or is that new since 3.0.+? If it's the version, I might be able to figure it out. Otherwise, I'll have to send you a diagnostic build to figure out what's actually working and when it stops.

**Comment by PersonTheCat** [comment]
Here's a debug build. Just run this and send me the full log. It should hopefully indicate which file is trying to load, get copied, etc. Also, which ore it's doing it for, which PropertyGroup it belongs to, and a bunch of other random pieces of information.

Thanks. 

[ore_stone_variants-3.0.5.zip](https://github.com/PersonTheCat/ore_stone_variants/files/2172427/ore_stone_variants-3.0.5.zip)

**Comment by pupnewfster** [comment]
[latest.log](https://github.com/PersonTheCat/ore_stone_variants/files/2172437/latest.log)

Another solution may be to add a config option to not do furnace mapping given I don't use it anyways.

**Comment by PersonTheCat** [comment]
I see. So, it definitely is related to the ore dictionary crash and not the texture loading crash. I wonder if this is related to the changes I was talking about earlier. I'll just change them back, for now. Let me think about this for a bit.

**Comment by pupnewfster** [comment]
I actually managed to figure it out. In a script I have that modifies the ore dictionary a little I by mistake still was referencing one of the ores that I had removed. After removing it from the script it works properly now.

**Comment by PersonTheCat** [comment]
Oh, great! Thanks for letting me know.
