### ISSUE TITLE
Crash on server start

### ISSUE THREAD

**Issue by pupnewfster** [PersonTheCat/ore_stone_variants#28]
When trying to start a forge server with version 3.0.0 I get this crash:
[crash-2018-07-08_18.19.47-server.txt](https://github.com/PersonTheCat/ore_stone_variants/files/2174183/crash-2018-07-08_18.19.47-server.txt)

Edit: I believe this is because https://github.com/PersonTheCat/ore_stone_variants/blob/master/src/main/java/personthecat/mod/properties/OreProperties.java#L545 should not be run on the server side, but is attempting to be run.

**Comment by PersonTheCat** [comment]
Thanks. This is a duplicate of one issue on CurseForge. A patch will be out either tonight or tomorrow.

**Comment by PersonTheCat** [comment]
I'm uploading the new version now. As this is a duplicate, I will close the issue. Please let me know if the fix does not also work for you or if new issues arise.
