### ISSUE TITLE
Wrong localization string for Thermal Foundation Tin

### ISSUE THREAD

**Issue by pupnewfster** [PersonTheCat/ore_stone_variants#3]
https://github.com/PersonTheCat/ore_stone_variants/blob/d2147cef98953fcbdb04990074a0766c09f6aec8/src/main/java/personthecat/mod/properties/DefaultProperties.java#L102

**Comment by PersonTheCat** [comment]
Haha woooow. Thanks.

**Comment by PersonTheCat** [comment]
I'm just going to close this. The current source on GitHub has fixed this problem.
