### ISSUE TITLE
Harvest levels are wrong

### ISSUE THREAD

**Issue by PaperTriangle** [PersonTheCat/ore_stone_variants#31]
The harvest levels of any blocks in quark material, or material that I add custom, are wrong. They're able to be mined by any level tool.

Example: Diamond Ore (Marble) can be mined with a wooden pickaxe.

**Comment by PersonTheCat** [comment]
Hm. That's odd. Took levels shouldn't change. I wonder if this is somehow related to background block imitation. I'll take another look at it today. Thanks for pointing this out!

**Comment by PersonTheCat** [comment]
So, this wound up being a really bizarre problem. When queried, some background blocks were not returning an appropriate tool type, meaning that any tool could be used for items to be dropped, meaning that no tool was also acceptable. I fixed it by detecting that and defaulting back to a pickaxe when it happens. A new build will be out tonight. If you're able to test it, please let me know if the problem has been fixed for you or if you encounter any other issues and I'll get on them as soon as possible.

Thanks again for your help!

**Comment by PaperTriangle** [comment]
Just checked it out, and the harvest levels are normal so this is fixed!

No worries! Thanks for the quick fix!
