### ISSUE TITLE
Request for the Addition of Quark's Basalt

### ISSUE THREAD

**Issue by Voxel-Friend** [PersonTheCat/ore_stone_variants#35]
As the title says. Any chance for basalt to get some love? The other stone variants in Quark work already out of the box. In the meantime I shall just add it through the config.

**Comment by Voxel-Friend** [comment]
Fair enough, didn't realize until after I made this issue about it being in the nether by default.  Either way, your amazing config allows me to do what I wanted to anyways, so kudos for that!

**Comment by PersonTheCat** [comment]
Hey, just letting you know, I think I am going to decide against this. I feel bad for saying that, but I just don't want to mess with the normal balance of the game by default. I'll still be working on Tinker's Construct again, though! I just have to figure out what the deal is with retrieving their block models. :/

**Comment by Voxel-Friend** [comment]
That's fair. Good luck with the mod!
