### ISSUE TITLE
Request for the Addition of Rustic's Slate

### ISSUE THREAD

**Issue by Voxel-Friend** [PersonTheCat/ore_stone_variants#36]
As the title says. Any chance for slate to get some love?

**Comment by Voxel-Friend** [comment]
Absolutely. Your config allows me to do it manually anyways, so this is just for other peoples benefit at this point.

**Comment by PersonTheCat** [comment]
Thanks for your awesome feedback! I really appreciate it. Support for Rustic is included by default in 3.9. That should get approved any minute now. I'll go ahead and close this, but please let me know of any other  issues or suggestions you have.
