### ISSUE TITLE
Crash on server

### ISSUE THREAD

**Issue by pupnewfster** [PersonTheCat/ore_stone_variants#44]
Version: 4.2

https://pastebin.com/XBYEjJtX

I have ran into similar issues in other projects I have worked on where there are issues with methods that never get used not being able to find the classes they need. This is because when it accesses the class it attempts to find it as they are used in the method signature. Assigning them to be Clientside only MAY work though you may have to just move the client side methods to a different class.

**Comment by PersonTheCat** [comment]
Damn it. You're right. Looks like it was ModelEventHandler#placeAllModels. Here's an early version with only that change, and then I'll upload this to CurseForge either tonight or tomorrow / Tuesday, depending on whether I get around to working on new mod support. 

[ore_stone_variants-4.2.1.zip](https://github.com/PersonTheCat/ore_stone_variants/files/2476969/ore_stone_variants-4.2.1.zip)

**Comment by pupnewfster** [comment]
The linked version works (or at least the server does not crash on startup anymore).
Thanks

**Comment by PersonTheCat** [comment]
Finally updated. I feel bad it took so long, but I wound up just having to forget about adding new mod support, for the meantime.
