### ISSUE TITLE
Every other time I go through a portal it causes massive world gen issues

### ISSUE THREAD

**Issue by DefinitelyNotFred** [PersonTheCat/ore_stone_variants#5]
So, for example, if I create a portal to the end, everything will look normal in the end. But if I then use a nether portal, I will get this:

![image](https://user-images.githubusercontent.com/30205205/38170505-063d3d9a-354d-11e8-827b-d63972e902dc.png)

An example of going back to the overworld after having gone somewhere else would look like this:
![image](https://user-images.githubusercontent.com/30205205/38170516-2d76110c-354d-11e8-9038-bec4614288a9.png)

I noticed this when I first installed your mod with the ore_stone_variants-1.10.jar but have tested it in the new ore_stone_variants-2.3.jar with the same result. You can look at the screenshots for my Forge version, etc. I suppose I should mention that my graphics card is a bit old. This is still reproducible if I have no other mods installed and have deleted the config file. When I tried reproducing this via the Legacy Aether mod portal, I was unaffected but when I used the Teletoro mod portal, which is much more clearly based on the Nether portals, I would have issues related to those above.

Here is a crash I got after fooling around in one of these bad-world-gen areas. This was with no other mods and I cut out a lot of repetitive stuff from the middle of the log so it wouldn't exceed the limit on pastebin: https://pastebin.com/hy8GVunD

**Comment by PersonTheCat** [comment]
Ahh. Okay, that makes sense. Seems like the advancements were causing even more problems than I thought. I'm not sure how this is possible, but I'll take another look at it soon. In the meantime, please try disabling advancements in the config file and let me know if that for sure reduces this problem for you. Thanks! 

-Cat

**Comment by DefinitelyNotFred** [comment]
That fixed it. I tried turning it back on again to make sure, and it did indeed break it again. Good luck figuring that one out.

**Comment by PersonTheCat** [comment]
I believe this has now been fixed. Please try build 2.4 as soon as you get the chance and let me know if it's working for you without disabling advancements. It should be out in the next 30 minutes to an hour. Thank you so much!

**Comment by DefinitelyNotFred** [comment]
Github doesn't like to give me notifications for some reason. I turned the config back on with the new build and whatever you did fixed it, thank you.
