### ISSUE TITLE
[Request]A way to Disable Vanilla Quartz Generation

### ISSUE THREAD

**Issue by Voxel-Friend** [PersonTheCat/ore_stone_variants#51]
I am currently trying to do some voodoo with how to obtain ores in my pack, and I want vanilla nether quartz to not generate but to be obtainable. I want only for OSV nether quartz to generate, but I don't have a way how. Could you possibly add a config option to do so?

**Comment by PersonTheCat** [comment]
Are you sure this isn't working? It's supposed to do this automatically whenever netherrack variants of quartz exist. Although, looking at it again, it seems like I never actually updated it to support the multiple blockstates, so it might only affect the first blockstate of any block (ore_stone_variats:x_ore:0). If so, this is a pretty simple thing to fix and I'll definitely try to look at it soon. I've been super busy with classes, but I should definitely have a little time throughout the week for things like that. I'll let you know.

**Comment by Voxel-Friend** [comment]
Sweet thanks. As a workaround, using COFH World seems to have the effect I need.

**Comment by PersonTheCat** [comment]
I believe this was fixed and not updated at some point, but it should definitely be working again in 5.0 due to block state flattening.
