### ISSUE TITLE
Biomes O' Plenty generation hax incomplete

### ISSUE THREAD

**Issue by Exsolutus** [PersonTheCat/ore_stone_variants#53]
Greetings. I've just begun digging into what this mod is capable of, and so far things look great.

I have found that the generation hax option for Biomes O' Plenty is incomplete. While it succeeds in disabling BoP gem generation in all BoP biomes, it neglects the fact that BoP also adds it's gems to vanilla biomes. 

The task can easily be done manually, but I thought I would make a note of it here for the developer to consider.

**Comment by Exsolutus** [comment]
Sorry about that. I bumped the enter key before I had a chance to write my post.

**Comment by PersonTheCat** [comment]
Ahhhh okay. Thanks, I didn't realize that. I'll take a look at it.

**Comment by Exsolutus** [comment]
I also just discovered BoP also adds Emeralds to some of it's biomes, such as Highlands.

**Comment by PersonTheCat** [comment]
Okay, so I am gonna mark this as an enhancement, but I'm still gonna need a little bit of time to look at these other bugs first (e.g. the server-side crash that still hasn't been released). I also want to see if I can come up with a better way to do this first, which would require replacing what's already there.

**Comment by PersonTheCat** [comment]
This was updated in 5.1-1.12 and is definitely working.
