### ISSUE TITLE
Crafttweaker support of oredictionary and this mod

### ISSUE THREAD

**Issue by kragnoth** [PersonTheCat/ore_stone_variants#55]
Crafttweaker can iterate through all members of an ore dictionary group.  However, it seems like the oredictionary is initialized in a stage after CrT runs scripts.

Would it be possible to move the oredict generation of this mod up the pipeline, or is that not possible due to the way blocks are generated?

Thanks

**Comment by PersonTheCat** [comment]
My preference has been to do everything I can as late as possible, given that I depend on a variety of other mods that operate at various stages throughout the load period. I could always try to make this change, but my only concern is that it would take me a long time to verify whether any problems have been caused. :/ Give me a bit to look into this one.

**Comment by kragnoth** [comment]
It looks like you had some functions in your code I could use straight in CrT so I'm not sure this is even a valid point I made anymore.

**Comment by kragnoth** [comment]
NP, found a solution in the code of JAOPCA for my side of things for the pack I'm working on.

Thanks

**Comment by PersonTheCat** [comment]
Oh cool, good to hear. I'll go ahead and close this issue.
