### ISSUE TITLE
Dense Ores Smelt To One Output

### ISSUE THREAD

**Issue by InsomniaKitten** [PersonTheCat/ore_stone_variants#56]
If a player were to silk touch a dense iron ore, for example, they cannot then smelt it into multiple ingots. The dense ore mechanic only accounts for multiple *drops* when mined *without* silk touch.

**Mod version:** [4.2](https://minecraft.curseforge.com/projects/ore-stone-variants/files/2626532)

**Comment by PersonTheCat** [comment]
Thanks for pointing this out! I never really intended for things to work like that, but I can see how it would be an improvement and will look into it soon.

**Comment by PersonTheCat** [comment]
Hey, there. Sorry this took me so long to get to. Just letting you know that I have now implemented this feature and an update should be out later today.
