### ISSUE TITLE
Disable vanilla stone/ore generation option doesn't work

### ISSUE THREAD

**Issue by kragnoth** [PersonTheCat/ore_stone_variants#57]
It will disable vanilla ore generation, but the only stone that generates is stone.  No gravel, no dirt, no diorite, etc.

This is on a pure vanilla with just ore stone variants install.  Forge 2796, ore stone varaints 4.2 for 1.12.2

**Comment by PersonTheCat** [comment]
Hello. I believe this is actually intended behavior. The reason for it is that OSV will actually spawn its own stone variants, instead. This is another one of those decisions that I sort of regret making as it's a bit unnecessary for this mod, but it's also a little too late to change it, at this point. Can you confirm the stone generation variables you're using? They should each be higher than -2. If they are and this is definitely still an issue, please feel free to send me your config and I'll try to reproduce it that way.
Also, feel free to join us on Discord. I get notifications there and usually will respond right away, if I'm not at work or just waking up.
Hope this helps!

**Comment by kragnoth** [comment]
Just JEI and Stone ore variants in the latest 2796 build of for 1.12

https://hastebin.com/ximifiwudi.bash

Absolutely no dirt, gravel, andesite, granite or diorite.  Only base stone:0 spawns
