### ISSUE TITLE
[Question/Suggestion] Config to Disable Replacement Ore Gen

### ISSUE THREAD

**Issue by Tetrajak** [PersonTheCat/ore_stone_variants#60]
Is there some way of disabling the automatic ore gen that the mod creates when ore variants are added to the config? If there isn't, there should be, because I'd rather not use the vanilla ore generation algorithms.

**Comment by PersonTheCat** [comment]
There used to be a way to get this to happen, but it was never intended. The only way to achieve this currently is by using Geolosys to spawn ores instead. However, I agree that the vanilla algorithm is inefficient and frankly doesn't produce very interesting shapes. Seeing as it would be so easy to do, I would be willing to add this as a feature. Check back soon.

**Comment by Tetrajak** [comment]
Thank you! I find your mod incredibly helpful for my modded setup!

**Comment by PersonTheCat** [comment]
This has been added as of 4.4, which will be out momentarily.
