### ISSUE TITLE
WorldGenProperties has no effect

### ISSUE THREAD

**Issue by shefla** [PersonTheCat/ore_stone_variants#64]
I'm trying to configure the generation of gold ore in the nether.
Using "gold_ore" in the "ore property mods" config section I got a zip to work with.
I then created and added a WorldGenProperties.json to configure the generation:
```json
{
	"blockCount" : 9,
	"chance" : 2,
	"minHeight" : 0,
	"maxHeight" : 32,
	"dimensionList" : [-1],
	"dimensionsAreBlacklist" : true,
	"additionalPropertyKeys" : ["netherProperties"],
	"netherProperties" :
	{
			"blockCount" : 9,
			"chance" : 40,
			"minHeight" : 0,
			"maxHeight" : 128,
			"dimensionList" : [-1]
	}
}
```
If I understand correctly this should allow gold ore to spawn from 0 to 128 in the nether but it's not the case.
I checked multiple times using world stripper and other worldgen settings but gold never appears above Y = 32.

**Comment by PersonTheCat** [comment]
Huh. I actually have a very similar setup that I use to test this feature with coal ore. Just retested and could not reproduce the issue. Anyway you could share your exact file structure with me?

**Comment by shefla** [comment]
Alright here is [my config](https://pastebin.com/EM804Rm5), as you can see I added gold_ore for netherrack and basalt in the "variant_adder" section.
In the "ore_stone_variants_mods" folder I have an archive named "minecraft_gold_ore.zip" which contains three files at the top level:
 * OreProperties.json (left untouched)
 * RecipeProperties.jon (left untouched)
 * WorldGenProperties.json (contents posted above)

**Comment by PersonTheCat** [comment]
Oh okay, I see. You need to use the original name of the ore properties, which in this case is just `gold_ore` and not `minecraft_gold_ore`. I know that's confusing and wish I could improve on that. When I eventually update to 1.14 or so, I'll be reworking a lot of these systems. 
Let me know if this does or does not work, though.

**Comment by shefla** [comment]
It works, thanks a lot for the quick response.
I would never been able to figure this out by myself since the archive name is auto generated.
Keep up the good work, your mod is awesome!

**Comment by PersonTheCat** [comment]
Oh cool. Thank you so much for the feedback! Feel free to join the Discord server, if you need help with anything else. https://discord.gg/fmnQgy
