### ISSUE TITLE
Ore Excavation, Veinminer?

### ISSUE THREAD

**Issue by EerieP** [PersonTheCat/ore_stone_variants#65]
Is there integration for these mods?

**Comment by PersonTheCat** [comment]
Hi, there. Sorry for ignoring these issues. I meant to look into why there were compatibility issues and I believe I just never figured it out and then forgot. Sorry about that! I've just been a little busy at work. I suspect that what's happening is that these mods are treating non-OSV blocks as OSV blocks, which causes them to try and do something they can't do. But I could be wrong, so I still need a little more time to investigate.
