### ISSUE TITLE
[Crash] with Geolosys 3.0.0

### ISSUE THREAD

**Issue by CactusDuud** [PersonTheCat/ore_stone_variants#69]
Minecraft version 1.12.2
OSV version 4.4

https://pastebin.com/P2qDJgL6

The recent big Geolosys update may mean some code needs to be tweaked.

**Comment by PersonTheCat** [comment]
This sounds like a reasonably easy fix. Just trying to get a workable build going for 1.14 first.

**Comment by Kamefrede** [comment]
Any update on this?

**Comment by Xelbayria** [comment]
I want to report similar issue to here. 
I was using 
-Forge-14.23.5.2847
-Geolosys 3.08
-Ore Stone Variant 4.5

It will need some tweaking as well.

**Comment by PersonTheCat** [comment]
Fixed in 4.6. That will be uploaded by the end of the day and should get approved by Monday.
