### ISSUE TITLE
Bedrock hardness isn't properly mimicked

### ISSUE THREAD

**Issue by DaedalusGame** [PersonTheCat/ore_stone_variants#78]
From my understanding, block properties should be mimicked to the best of the mod's ability? But when adding a block group containing bedrock, the generated ore will still be breakable and not, as expected, unbreakable.

**Comment by PersonTheCat** [comment]
This is a bug, for sure. It just merges the two blocks' hardness levels and doesn't account for whether either is actually unbreakable. I'll try to fix it soonish.

**Comment by PersonTheCat** [comment]
Fixed in 4.6. I'll upload that soon and it should get approved by Monday.
