### ISSUE TITLE
Config QOL change

### ISSUE THREAD

**Issue by pupnewfster** [PersonTheCat/ore_stone_variants#8]
It would be nice if there was a way to add all custom ores to new variants similar to how you can specify a specific mod name "vanilla,netherrack" or "basemetals,netherrack". Maybe make it something like "custom,netherrack" to add all ores specified in ore_stone_variants_mods without having to manually add them for each type.

This isn't an urgent change but would be a nice quality of life feature.

Also being able to specify multiple drops/drop rates for custom blocks because of mods like NuclearCraft or Flux Networks adding more drops to ores like Redstone.

Edit: And potentially even an option to have different spawn locations for the ores based on the dimension/biome. (Draconic Evolution Draconium ore spawns very frequently by default in the end but extremely rarely in the overworld)

**Comment by PersonTheCat** [comment]
The first one should be pretty easy. I already have a property group holder object that I use to determine which ores are associated with any given mod. I would probably just make it to where users can add a new package under /config/ore_stone_variants_mods/,  ending in "_group," with a file containing all of the desired ore types. Or, I might add a field to OreProperties.json, which would be a string specifying the mod name / group. The only problem is I need to work out a way to not have blocks get created or spawned twice. 

I'm not sure what you mean about multiple drops or drop rates, though. Do you mean relative to certain tools, fortune level, or something else? 

The third one definitely is possible in a way, although I agree it could be a little bit more advanced / efficient. You can always just create a new block with the same properties as the original block and give it different spawn conditions, but the same texture, language key, and everything else. Ideally, this would be possible using only one block (i.e. fewer system resources), though. You can see where I tried to do something similar with Thermal Foundation's copper ore, which spawns differently at different altitudes and in ocean biomes, but it's a little too convoluted of a solution and isn't flexible at all. So, I still need to work out a better solution for that!

Thanks! -Cat

**Comment by pupnewfster** [comment]
Ok, I will think more about it later, but for the second one. What I meant is Flux Networks adds a chance of having flux drop when redstone is broken is dropped in addition. And similar things like that.

**Comment by pupnewfster** [comment]
One way to do number three is you could allow multiple WorldGenProperties files (not sure how you would name them) and then add a dimension white list that if empty does all the dimensions enabled in the main config.

**Comment by PersonTheCat** [comment]
How about something like [this](https://pastebin.com/ZcWVaAB7)? Should be fairly easy to implement.

**Comment by pupnewfster** [comment]
That should work fine.

**Comment by PersonTheCat** [comment]
It may have taken quite a few lines, but [OreProperties can now hold multiple DropProperties](https://github.com/PersonTheCat/ore_stone_variants/blob/e3f8a0d40a1d6be27fcffe9a3df6ab2e7e1767f1/src/main/java/personthecat/mod/properties/OreProperties.java). I'll do custom PropertyGroups and multiple WorldGenProperties next.

**Comment by pupnewfster** [comment]
Sounds good.

**Comment by PersonTheCat** [comment]
As I believe these have been implemented, I'm going to close this issue.
