### ISSUE TITLE
Crash report 

### ISSUE THREAD

**Issue by SpGilbert** [PersonTheCat/ore_stone_variants#81]
https://paste.dimdev.org/ebovutidil.mccrash when I was resorting to my mods I cut them in half. now ore stone variants is crashing for some reason.

**Comment by PersonTheCat** [comment]
It says you're referring to an ore block or OreProperties object that doesn't exist, called "mca:rose_gold_ore." I don't see MCA installed, so that may be why.

**Comment by SpGilbert** [comment]
oh
