### ISSUE TITLE
Adding mineralogy chalk crashes game

### ISSUE THREAD

**Issue by drago87** [PersonTheCat/ore_stone_variants#84]
i tried to add mineralogy:chalk to the block groups under mineralogy and the game crashes with
[crash-2019-10-28_13.00.46-client.txt](https://github.com/PersonTheCat/ore_stone_variants/files/3778574/crash-2019-10-28_13.00.46-client.txt)

**Comment by PersonTheCat** [comment]
Block groups can only hold 16 states until 5.0. you'll have to put it in a different group.
