### ISSUE TITLE
Crash while loading OSV 5.0b1 with Forge 28.1.76

### ISSUE THREAD

**Issue by vico93** [PersonTheCat/ore_stone_variants#86]
Crash report: https://paste.dimdev.org/jokamexepe.rb

The crash happens while starting the game.

Windows 10 x64

**Comment by vico93** [comment]
Fixed deleting `config\osv` and relaunching the game. Dont know what happened here....

**Comment by PersonTheCat** [comment]
Hey, thank you so much for reporting this! You aren't the only one who's reported this, actually. There must be something strange going on related to the first time this game loads. If not that, then maybe it has to do with the way mods are loaded in parallel now or something. Not sure, but I'll try to figure it out soon.

**Comment by vico93** [comment]
Yeah, that was the first time i was running MC with osv installed
