### ISSUE TITLE
Crash when initializing with Quark

### ISSUE THREAD

**Issue by Foreck1** [PersonTheCat/ore_stone_variants#89]
https://paste.dimdev.org/pufevojada.mccrash

Game crashes due to being "Unable to find one or more of the blocks listed in block group "quark.""

**Comment by PersonTheCat** [comment]
Do you have one of Quark's stone types disabled? If so, you just need to go into the config file for OSV and remove it from the list of block groups. If not, let me know and I'll help you figure it out.

**Comment by Foreck1** [comment]
Indeed, both Quark and Rustic support had to be disabled, It didn't occur to me that a config had actually been created. Thanks for your fast response and support, on a final note, I think it would be great if the crash log indicated to the player that a config file does indeed generate even thought the game crashes on startup.
