### ISSUE TITLE
Lapis Ore variants wrong drops

### ISSUE THREAD

**Issue by Awec4** [PersonTheCat/ore_stone_variants#9]
When broken with a pickaxe the Lapis Ore variants and dense ore variants drop ink sacs instead of Lapis.
Also, all Lapis ores only smelt to 1 Lapis.

**Comment by PersonTheCat** [comment]
Hello. Thanks for pointing these out! The ink sac problem was a pretty easy fix. I just uploaded a new version, 2.8, to curseforge.com. Please try it when it gets processed and let me know if that fixes things for you as well. As for lapis ores smelting to 1 lapis, I believe this is how things work in vanilla. I will not be changing it by default, but I have made made a workaround for you using the mods system. You can download the zip file below and place it in /config/ore_stone_variants_mods/. If you don't want them to give 4, just open it up, then open RecipeProperties.json, and change "quantity" to however much you want. 

Hope this helps! -Cat

[lapis_ore.zip](https://github.com/PersonTheCat/ore_stone_variants/files/1916954/lapis_ore.zip)
