### ISSUE TITLE
Error when try with Better with mods(1.12.2)(OSV consumes all memories)

### ISSUE THREAD

**Issue by spb00000** [PersonTheCat/ore_stone_variants#93]
![image](https://user-images.githubusercontent.com/68857611/91684823-88704380-eb93-11ea-8397-c8c515013e99.png)

Error that OSV mod consumes too many memory (and eventually crashed)
or Error when 'There was a severe problem during mod loading that has caused the game to fail'

[crashlog 1](https://pastebin.com/v0Hhfrr2)

[crashlog 2](https://pastebin.com/wkSbjRyB)

OSV mod consume too many memories, and it keeps making crash

**Comment by spb00000** [comment]
I tried some, This state cause crash.
![image](https://user-images.githubusercontent.com/68857611/91687115-f61f6e00-eb99-11ea-9887-dca453b7ec02.png)

**Comment by PersonTheCat** [comment]
Hello. Please share the exact configuration you're using, along with any presets you've created or changed. I will try and figure out if there's a memory leak later. Just post them here.

**Comment by PersonTheCat** [comment]
Hello again. I have discovered this to be a bug with copying `.mcmeta` files resulting in an infinite loop in the 1.12 version only. I have fixed this. Feel free to try it and let me know if it works for you too. Thanks for your help!

[Ore Stone Variants-5.4.zip](https://github.com/PersonTheCat/ore_stone_variants/files/5153244/Ore.Stone.Variants-5.4.zip)

**Comment by spb00000** [comment]
It worked! Great! Thank you!

**Comment by PersonTheCat** [comment]
Great! Thanks again!
