### ISSUE TITLE
I found a new purpose of OSV

### ISSUE THREAD

**Issue by spb00000** [PersonTheCat/ore_stone_variants#94]
![2020-08-31_18 36 03](https://user-images.githubusercontent.com/68857611/91706518-773a2d80-ebb9-11ea-914c-fe91c2673332.png)

It can make decoration blocks infinitely!
Could you make these features into another mod?

[config.zip](https://github.com/PersonTheCat/ore_stone_variants/files/5149577/config.zip)
here's config that I used.

**Comment by PersonTheCat** [comment]
Hello. I'm not exactly sure what you mean by putting these features into a new mod. Do you mean take the exact blocks you've added through OSV and make a dedicated mod for them?

**Comment by spb00000** [comment]
I just found some possibility it could be a cosmetic mod like chisel mod. but not like other mods, It will be fully configurable and can add or delete pattern easily? It's just a hypothesis...

**Comment by PersonTheCat** [comment]
I gotcha. This is not a bad idea, but unfortunately, I don't think I have the time to pull it off. :/ I'm gonna have to decline.
