### ISSUE TITLE
OSV doesn't work well with JEI  (1.16.2)

### ISSUE THREAD

**Issue by DatrixTHLK** [PersonTheCat/ore_stone_variants#95]
Hi again,

I don't get why, but your mod seems to now overwrite JEI in that I can't see the GUI on the right side of the inventory screen while your mod is in use in my mods list. When I take your mod out I can see JEI GUI located to the right of my inventory screen. In other words JEI and OSV aren't compatible as of right now.

Minecraft: 1.16.2
Forge: 33.0.37
OSV: 5.6

I don't know if there's an FML log that will help with any of this seeing as there isn't an error causing my game to CTD.

**Comment by PersonTheCat** [comment]
This one was surprisingly tough to catch, but ultimately I discovered that it came from registering both the furnace recipe and blasting recipe to the same ID. Oops! Really glad you pointed it out. Let me know if you find anything else.

[Ore Stone Variants-5.6-1.16.2.zip](https://github.com/PersonTheCat/ore_stone_variants/files/5180529/Ore.Stone.Variants-5.6-1.16.2.zip)

**Comment by DatrixTHLK** [comment]
Will do and thanks for the update and response. I appreciate the hard work you do
