### ISSUE TITLE
[suggestion] dense ore min drop

### ISSUE THREAD

**Issue by Biviho** [PersonTheCat/ore_stone_variants#98]
hi, it would be a nice addition to have a config for a minimum drop chance number for dense ore, because if they are used as an additional reward for fortune enchantment, it is a bit sad when your shitty luck roll you a 1 and you get no bonus

**Comment by PersonTheCat** [comment]
Yes, definitely. I can add this to 1.14 / 1.16 no problem. Thanks for the suggestion!

**Comment by Biviho** [comment]
are you not supporting 1.12 anymore?

**Comment by PersonTheCat** [comment]
I am supporting it, but not adding any major features to it. I did add this feature to the 1.12 version since it was pretty minor.
